# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 323e1606b9df069a9729b3c98f0e6117e8c5deba4ea6522ba48d174593c6c8adf40010802ae4b81f99f9a719b5ce60f4bba3d72ab51ee9c66f42ce61e9a48a25

test:
  secret_key_base: 8ccb36e4b073052b0b702e989bc9f15e9ae7269815433624a5acae88314ab14f798760933aa57980bd09c4895c7c3638dc99e1d479932ac664e1fa1b85412918

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
